services:
  forti:
    build: .
    hostname: forti
    restart: unless-stopped
    tty: true
    volumes:
      - ./config:/etc/openfortivpn/config:ro
      - ./tinyproxy.conf:/etc/tinyproxy/tinyproxy.conf:ro
    devices:
      - /dev/net/tun:/dev/net/tun
      - /dev/ppp:/dev/ppp
    cap_add:
      - NET_ADMIN
    ports:
      - 127.0.0.1:8888:8888
